### PR TITLE
Add guise2024

### PR DESCRIPTION
**Pull request by cvanderaa**
[TDP-43-stratified single-cell proteomics of postmortem human spinal motor neurons reveals protein dynamics in amyotrophic lateral sclerosis](http://dx.doi.org/10.1016/j.celrep.2023.113636)

I still need to send data to ExperimentHub so do not merge, pls.

### CODE REVIEW

**Comment by cvanderaa** [comment]
Note this PR also adds cellenONE data to the `leduc2022_pSCoPE`. I sent mail to EH this morning and am waiting for the credentials.

**Comment by cvanderaa** [comment]
The data set are live! I consider this PR completed. @lgatto let me know if I need to adapt something. I'll push to bioconductor (and subsequently bump version) upon merge.

**Comment by lgatto** [comment]
Go ahead !

**Review by lgatto — APPROVED** [review]

**Comment by cvanderaa** [comment]
(changes were pushed to Bioconductor and version bumped)

**Pull request merged**
